set PATH "$DEV/dotfiles/fish/bin" $PATH
set PATH "/usr/local/bin" $PATH
set PATH "/usr/local/sbin" $PATH
set PATH "/usr/local/mysql/bin" $PATH
set PATH "/opt/nginx/sbin" $PATH
set PATH "/opt/local/bin" $PATH
set PATH "/opt/local/sbin" $PATH
set PATH "/usr/local/opt/gnu-tar/libexec/gnubin" $PATH
set PATH "$HOME/.nodenv/bin" $PATH
set PATH "$HOME/.rbenv/bin" $PATH
set PATH "$HOME/.rbenv/shims" $PATH
set PATH "/System/Library/Frameworks" $PATH
set PATH $MYSQL_PATH $PATH
set PATH $POSTGRES_PATH $PATH
set PATH $JAVA_HOME/bin $PATH
